version: '3.3'

services:
    parser_nginx:
        image: nginx:1.17
        ports:
            - 8100:80
        volumes:
            - .:/var/www/html
            - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ../docker/nginx/general.conf:/etc/nginx/nginx.conf
        depends_on:
            - parser_php

    parser_php:
        build: ../docker/php
        depends_on:
            - parser_database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=${DATABASE_URL}
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ../php-cs-fixer:/usr/local/bin/php-cs-fixer

    parser_database:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        expose:
            - "3306"
        entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
        volumes:
            - ../docker/mysql/database/data:/var/lib/mysql
            - ../docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    composer:
        restart: 'no'
        image: composer
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html